name: Build and push to ECR

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      aws-region:
        required: true
        type: string
    secrets:
      nuget-config-including-pat:
        required: true
      aws-account-id:
        required: true

permissions:
  contents: write
  pull-requests: write
  id-token: write

env:
  # Space-separated list of tags
  TAG_LIST: "latest"

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # Using IAM role based for OIDC identity provider
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ inputs.aws-region }}
          role-to-assume: arn:aws:iam::${{ secrets.aws-account-id }}:role/github-actions-role
      - run: aws sts get-caller-identity

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Automatic Tagging of Releases part 1
        id: latest-git-tag
        run: |
          bash versioning/git_latest.sh

      - name: Automatic Tagging of Releases part 2
        id: increment-git-tag
        run: |
          bash versioning/git_update.sh -v ${{ steps.latest-git-tag.outputs.CURRENT-GIT-TAG }} -f ${{ steps.latest-git-tag.outputs.GIT-TAG-FOUND}}

      - name: Create nuget.config contents from secret
        run: |
          bash versioning/create_nuget_config.sh ${{ secrets.nuget-config-including-pat }}

      - name: Set up env values
        env:
          ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
          REPO_URL=`git remote get-url origin`
          IMAGE_TAG=v${{ steps.increment-git-tag.outputs.GIT-TAG }}
          GIT_HASH=`git rev-parse --short "$GITHUB_SHA"`
        run: echo "env vars set up ok"

      - id: buildImage
        name: Build image
        run: |
          docker build . --no-cache \
          --tag $ECR_REGISTRY/${{ inputs.image-name }}:$IMAGE_TAG \
          --label defra.cdp.git.repo.url="$REPO_URL" \
          --label defra.cdp.service.name="${{ inputs.image-name }}" \
          --label git.hash="$GIT_HASH"

      - name: Tag image
        run: |
          # Add Git hash to tag list
          EXTRA_TAG_LIST="$TAG_LIST $GIT_HASH"
          echo "Tags are $TAG_LIST"
          for TAG in $EXTRA_TAG_LIST
          do
            echo "creating tag $TAG"
            docker image tag $ECR_REGISTRY/${{ inputs.image-name }}:$IMAGE_TAG $ECR_REGISTRY/${{ inputs.image-name }}:$TAG
          done

      - name: Push docker image
        run: |
          ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG=v${{ steps.increment-git-tag.outputs.GIT-TAG }}
          docker image push $ECR_REGISTRY/${{ inputs.image-name }}:$IMAGE_TAG
          for TAG in $TAG_LIST
          do
            docker image push $ECR_REGISTRY/${{ inputs.image-name }}:$TAG
          done

      - name: Cleanup - remove nuget.config as it contains sensitive info
        if: always()
        run: |
          bash versioning/remove_nuget_config.sh
