name: Build NuGet and unit test

on:
  workflow_call:
    inputs:
      project-name:
        required: true
        type: string
    secrets:
      nuget-config-including-pat:
        required: true

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  build:
    name: Build NuGet and Unit Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Get common repo
        uses: actions/checkout@v3
        with:
          repository: defra-cdp-sandpit/cdp-workflows
          path: temp_scripts

      - name: Create nuget.config contents from secret
        run: |
          bash temp_scripts/scripts/create_nuget_config.sh ${{ secrets.nuget-config-including-pat }}

      - name: Temp output of nuget.config
        run: |
          ls -al *
          cat nuget.config

      - name: Restore dependencies
        run: dotnet restore ./${{ inputs.project-name }}.sln

      - name: Build
        run: dotnet build ./${{ inputs.project-name }}.sln --no-restore

      - name: Test
        run: dotnet test ./${{ inputs.project-name }}.sln --no-build --verbosity normal

      - name: Cleanup - remove nuget.config as it contains sensitive info
        if: always()
        run: |
          bash temp_scripts/scripts/remove_nuget_config.sh
