name: Pull from ECR and run UI tests

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      aws-region:
        required: true
        type: string
    secrets:
      aws-account-id:
        required: true

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  build:
    name: Pull and Integration Test Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install npm
        run: npm install

      # Using IAM role based for OIDC identity provider
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ inputs.aws-region }}
          role-to-assume: arn:aws:iam::${{ secrets.aws-account-id }}:role/github-actions-role
      - run: aws sts get-caller-identity

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Get common repo
        uses: actions/checkout@v3
        with:
          repository: defra-cdp-sandpit/cdp-workflows
          path: temp_scripts

      - name: Find Most Recent Tag
        id: latest-git-tag
        run: |
          bash temp_scripts/scripts/git_latest.sh

      - name: Pull pre-built image and start container
        env:
          FULL_IMAGE_NAME_AND_TAG: ${{ steps.login-ecr.outputs.registry }}/${{ inputs.image-name }}:v${{ steps.latest-git-tag.outputs.CURRENT-GIT-TAG }}
        run: docker-compose -f docker-compose.yml -f docker-compose.run.yml up -d

      - name: Wait for Docker container to finish starting up (timeout if not up in 15 secs)
        uses: iFaxity/wait-on-action@v1
        with:
          resource: http://localhost:3000
          timeout: 15000

      # In case there are any issues with the containers, the logs can be retrieved using this action
      #- name: Dump docker logs
      #  uses: jwalton/gh-docker-logs@v2

      - name: Run UI Tests
        run: npm run wdio
