name: Build and push to ECR

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install npm
        run: npm install

      - id: buildImage
        name: Build image
        run: |
          docker build . --no-cache \
          --tag ${{ inputs.image-name }}:pipeline

      - name: Run image and start container as backend API
        env:
          FULL_IMAGE_NAME_AND_TAG: ${{ inputs.image-name }}:pipeline
        run: docker-compose -f docker-compose.yml -f docker-compose.run.yml up -d

      - name: Wait for Docker container to finish starting up (timeout if not up in 15 secs)
        uses: iFaxity/wait-on-action@v1
        with:
          resource: http://localhost:3000
          timeout: 15000

      # In case there are any issues with the containers, the logs can be retrieved using this action
      #- name: Dump docker logs
      #  uses: jwalton/gh-docker-logs@v2

      - name: Build in order to generate nunjucks etc
        run: npm run build

      - name: Run Unit Tests
        run: npm run test

      - name: Run UI Tests
        run: npm run wdio
